version: '3'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    volumes:
      - n8n-data:/home/node/.n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    restart: unless-stopped

volumes:
  n8n-data:
